### ISSUE TITLE
Missing XML declaration on GPX export?

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#168] opened 2018-04-22 13:16 UTC
Ref. support email. Apparently `<?xml version="1.0"?>` is missing, preventing importers to dismiss the GPX file. Pls investigate and fix if true.

@MichaelsJP Feel free to re-assign, not sure about your workload these days..

**Comment by MichaelsJP** [comment] 2018-04-30 15:58
@nilsnolde From my point of view the export looks fine. Below I added a simple API call I did myself. Do you know who raised that issue?
[gpx_route_example.txt](https://github.com/GIScience/openrouteservice/files/1961271/gpx_route_example.txt)

**Comment by rabidllama** [comment] 2018-05-30 07:21
@nilsnolde can you confirm if this is still a problem or can we close it?

**Comment by ghspenguin** [comment] 2018-06-04 21:16
@rabidllama 
Hi! I'm the one who has reported the problem to @nilsnolde and on my platform the problem still persists. With both browsers, Firefox and Chromium on a Linux Mint Box.
When I try to export a route, the XML declaration is missing. As an additional information I can say, that my export file has no line breaks.
Maybe interesting for you?

**Comment by MichaelsJP** [comment] 2018-08-23 17:53
@ghspenguin Can you already say something if the problem still exists in the current development branch?
Sadly I can't reproduce the error on my machine and no one else got this problem so far...

**Comment by ghspenguin** [comment] 2018-09-01 12:34
@MichaelsJP 
Hi! Is there an installation of the development site with public access? I've nor resources to install a development version locally.
In my case, at http://maps.openrouteservice.org the problem was reproduceable on different machines with different browsers (IE, Firefox, Chromium) and on linux and windows.
Maybe you can send me an link to the development site, so I can test it in the way I would use the service?

**Comment by rabidllama** [comment] 2018-09-03 07:12
@ghspenguin @MichaelsJP I have just had a quick look and it seems this is actually an issue with the front-end. I presume that you are using maps.openrouteservice.org to produce the route and then selecting to export the route as opposed to directly querying the API?  When I do it from the front end I get the same issue with a missing declaration, but when querying the api I get a correct response with the xml tag. I will pass this on to the front end developers to investigate further.

**Comment by rabidllama** [comment] 2018-09-03 07:18
I will close this issue here as the front-end needs to address this bug

**Closed as completed by rabidllama** 2018-09-03 07:18 UTC
Labels: investigate
