### ISSUE TITLE
If info in app.config is missing, GPX build will fail, make it optional

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#80] opened 2018-01-19 11:38 UTC

**Comment by TimMcCauley** [comment] 2018-01-19 16:50
Let's make this optional ;-)

**Comment by rabidllama** [comment] 2018-01-21 09:12
I think the problem is that if we are sticking to the gpx schema, than all of the extra info that is in the app.config is mandatory, so strictly speaking, if that information is not there, then what we return isn't gpx

**Comment by TimMcCauley** [comment] 2018-01-21 16:39
Roger, shall we hard core something default which can be overwritten by app.config?

**Comment by MichaelsJP** [comment] 2018-01-22 21:18
I added some logic inside the GpxRoutingResponseWriter to check if the config variables are set. if not they are left blank and an error is printed out to the user console e.g. "Config parameter support_mail is missing" . 

I omitted a classic try catch because the error handling breaks the gpx routine.
@TimMcCauley We could insert some generic values and/or skip the printing...

Generally speaking, all the missing values wouldn't break the gpx shema as long as the header is set correctly

**Comment by TimMcCauley** [comment] 2018-01-23 09:13
Roger, thanks! Can you create a PR?

**Comment by rabidllama** [comment] 2018-01-29 12:09
Fixed in PR #84

**Closed as completed by rabidllama** 2018-01-29 12:09 UTC
