### ISSUE TITLE
Docker Installation Issue - Caused by: java.net.BindException: Address already in use (Bind failed)

### ISSUE THREAD

**Issue by ImranHugo** [GIScience/openrouteservice#753] opened 2020-06-24 04:35 UTC
I am trying to deploy the OpenRouteService onto an Azure VM.  The steps I followed:

1. Provision VM (Standard B2s (2 vcpus, 4 GiB memory)) - (Linux (ubuntu 16.04))
2. Prep VM by installing Docker and Docker-compose
3. clone repo
4. cd docker && docker-compose up

---
#### Here's what I got
~/openrouteservice/docker$ docker-compose up
Pulling ors-app (openrouteservice/openrouteservice:latest)...
latest: Pulling from openrouteservice/openrouteservice
e9afc4f90ab0: Pull complete
989e6b19a265: Pull complete
af14b6c2f878: Pull complete
5573c4b30949: Pull complete
fb1a405f128d: Pull complete
197b0f525c26: Pull complete
f133ed18caca: Pull complete
d28b68718b19: Pull complete
fe6d3f98c013: Pull complete
8a7ce9f4f98d: Pull complete
f8c867d05321: Pull complete
5807e68ad520: Pull complete
dcfe83d6ff11: Pull complete
Digest: sha256:a4f8e1554cc5176e49547fbe9cfdb2e9507024c7ce7960dfa5ddb0d2318cec14
Status: Downloaded newer image for openrouteservice/openrouteservice:latest
Creating ors-app ... done
Attaching to ors-app
ors-app    | ### Package openrouteservice and deploy to Tomcat ###
ors-app    | Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"
ors-app    | java.lang.ClassNotFoundException: org.apache.juli.ClassLoaderLogManager
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$1.run(LogManager.java:195)
ors-app    |    at java.util.logging.LogManager$1.run(LogManager.java:181)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.<clinit>(LogManager.java:181)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Can't load log handler "1catalina.org.apache.juli.AsyncFileHandler"
ors-app    | java.lang.ClassNotFoundException: 1catalina.org.apache.juli.AsyncFileHandler
ors-app    | java.lang.ClassNotFoundException: 1catalina.org.apache.juli.AsyncFileHandler
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:965)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.addLogger(LogManager.java:1165)
ors-app    |    at java.util.logging.LogManager$2.run(LogManager.java:349)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
ors-app    |    at java.util.logging.LogManager.getLogManager(LogManager.java:378)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Can't load log handler "1catalina.org.apache.juli.AsyncFileHandler"
ors-app    | java.lang.ClassNotFoundException: 1catalina.org.apache.juli.AsyncFileHandler
ors-app    | java.lang.ClassNotFoundException: 1catalina.org.apache.juli.AsyncFileHandler
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:965)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
ors-app    |    at java.util.logging.LogManager.access$1500(LogManager.java:145)
ors-app    |    at java.util.logging.LogManager$RootLogger.addHandler(LogManager.java:1655)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:980)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.addLogger(LogManager.java:1165)
ors-app    |    at java.util.logging.LogManager$2.run(LogManager.java:349)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
ors-app    |    at java.util.logging.LogManager.getLogManager(LogManager.java:378)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Can't load log handler "2localhost.org.apache.juli.AsyncFileHandler"
ors-app    | java.lang.ClassNotFoundException: 2localhost.org.apache.juli.AsyncFileHandler
ors-app    | java.lang.ClassNotFoundException: 2localhost.org.apache.juli.AsyncFileHandler
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:965)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
ors-app    |    at java.util.logging.LogManager.access$1500(LogManager.java:145)
ors-app    |    at java.util.logging.LogManager$RootLogger.addHandler(LogManager.java:1655)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:980)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.addLogger(LogManager.java:1165)
ors-app    |    at java.util.logging.LogManager$2.run(LogManager.java:349)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
ors-app    |    at java.util.logging.LogManager.getLogManager(LogManager.java:378)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Can't load log handler "3manager.org.apache.juli.AsyncFileHandler"
ors-app    | java.lang.ClassNotFoundException: 3manager.org.apache.juli.AsyncFileHandler
ors-app    | java.lang.ClassNotFoundException: 3manager.org.apache.juli.AsyncFileHandler
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:965)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
ors-app    |    at java.util.logging.LogManager.access$1500(LogManager.java:145)
ors-app    |    at java.util.logging.LogManager$RootLogger.addHandler(LogManager.java:1655)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:980)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.addLogger(LogManager.java:1165)
ors-app    |    at java.util.logging.LogManager$2.run(LogManager.java:349)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
ors-app    |    at java.util.logging.LogManager.getLogManager(LogManager.java:378)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Can't load log handler "4host-manager.org.apache.juli.AsyncFileHandler"
ors-app    | java.lang.ClassNotFoundException: 4host-manager.org.apache.juli.AsyncFileHandler
ors-app    | java.lang.ClassNotFoundException: 4host-manager.org.apache.juli.AsyncFileHandler
ors-app    |    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
ors-app    |    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
ors-app    |    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:965)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
ors-app    |    at java.util.logging.LogManager.access$1500(LogManager.java:145)
ors-app    |    at java.util.logging.LogManager$RootLogger.addHandler(LogManager.java:1655)
ors-app    |    at java.util.logging.LogManager$5.run(LogManager.java:980)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
ors-app    |    at java.util.logging.LogManager.addLogger(LogManager.java:1165)
ors-app    |    at java.util.logging.LogManager$2.run(LogManager.java:349)
ors-app    |    at java.security.AccessController.doPrivileged(Native Method)
ors-app    |    at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
ors-app    |    at java.util.logging.LogManager.getLogManager(LogManager.java:378)
ors-app    |    at java.util.logging.Logger.demandLogger(Logger.java:448)
ors-app    |    at java.util.logging.Logger.getLogger(Logger.java:502)
ors-app    |    at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9001; nested exception is:
ors-app    |    java.net.BindException: Address already in use (Bind failed)
ors-app    | sun.management.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 9001; nested exception is:
ors-app    |    java.net.BindException: Address already in use (Bind failed)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:262)
ors-app    |    at sun.management.Agent.startAgent(Agent.java:452)
ors-app    | Caused by: java.rmi.server.ExportException: Port already in use: 9001; nested exception is:
ors-app    |    java.net.BindException: Address already in use (Bind failed)
ors-app    |    at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
ors-app    |    at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
ors-app    |    at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
ors-app    |    at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
ors-app    |    at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
ors-app    |    at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
ors-app    |    at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:173)
ors-app    |    at sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:816)
ors-app    |    at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:468)
ors-app    |    ... 2 more
ors-app    | Caused by: java.net.BindException: Address already in use (Bind failed)
ors-app    |    at java.net.PlainSocketImpl.socketBind(Native Method)
ors-app    |    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
ors-app    |    at java.net.ServerSocket.bind(ServerSocket.java:390)
ors-app    |    at java.net.ServerSocket.<init>(ServerSocket.java:252)
ors-app    |    at java.net.ServerSocket.<init>(ServerSocket.java:143)
ors-app    |    at sun.rmi.transport.proxy.RMIDirectSocketFactory.createServerSocket(RMIDirectSocketFactory.java:45)
ors-app    |    at sun.rmi.transport.proxy.RMIMasterSocketFactory.createServerSocket(RMIMasterSocketFactory.java:345)
ors-app    |    at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)
ors-app    |    at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
ors-app    |    ... 11 more
ors-app exited with code 0

Just wondering if there is something extra I need to do to enable something on the linux VM.  When configuring this on my local machine (Wndows 10), the docker daemon pops up a message asking me to enable sharing of volumes etc.  Just wondering if this has anything to do with the problem on the linux VM?

**Comment by nilsnolde** [comment] 2020-06-24 07:18
When you look in the trace, you see a few `Port already in use: 9001; nested exception is: ors-app | java.net.BindException: Address already in use (Bind failed)`. That's the port for JMX, but it's not exposed by default in the `docker-compose.yml`.. That's really weird, since internally in the container there shouldn't be anything using port 9001. Do you use `network_mode: host` or smth for docker?

**Comment by ImranHugo** [comment] 2020-06-24 07:26
Hi Team

This was a completely new VM with nothing installed on it at all.  I provisioned it this morning with th purpose of creating our hosted environment for doing ORS Matrix for Australia in our Azure account.

**Comment by nilsnolde** [comment] 2020-06-24 07:41
Only thing I can think of that there's some newer base image for Ubuntu which runs some crap on port 9001. That's hard to imagine as well.. I can't reproduce locally and have no clue as to what could be the problem..

**Comment by ImranHugo** [comment] 2020-06-24 09:26
I dropped the Azure VM completely and provisioned a new Docker VM at vultr.  This works like a charm here.  Not sure what was up with the Azure VM.  Maybe related to the version of ubuntu I selected on Azure vs Vultr.  Vultr base image for docker is 18.04 but Azure I selected 16.04.

Thanks for your support.

**Comment by rabidllama** [comment] 2020-07-21 13:02
I guess it must be some strange thing that they have running by default in their image (we have used both Ubuntu 16.04 and 18.04 with no issues).

Glad you got it working though, so I will close the issue but if there are any other issues, just let us know

**Closed as completed by rabidllama** 2020-07-21 13:02 UTC
