### ISSUE TITLE
Bearings property cannot be used on any profile

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#702] opened 2020-04-30 06:10 UTC
#### Here's what I did

Requested a route that made use of the bearings API parameter, i.e. 
```
https://api.openrouteservice.org/v2/directions/cycling-mountain

{
	"coordinates": [[8.681495,49.41461],[8.687872,49.420318]],
	"bearings": [[25,30],[90,20]]
}
```

---
#### Here's what I got

An error message saying that headings is not supported
```
{
    "error": {
        "code": 2099,
        "message": "Heading is not (fully) supported for CHGraph. See issue #483"
    },
    "info": {
        "engine": {
            "version": "6.1.0",
            "build_date": "2020-04-27T04:45:15Z"
        },
        "timestamp": 1588226836862
    }
}
```

---
#### Here's what I was expecting

That the routing process takes the preferred bearings into account as has previously been the case 

---
#### Here's what I think could be improved

It seems there has been some change in the logic as previously when bearings was passed the system dropped out of using CH as bearings were not possible with that. Now this is not the case and when bearings are provided it does not fall back. This can be seen by adding the `"preference": "shortest"` parameter which then falls out of CH as shortest does not have the CH graph built

**Comment by PeterDieter** [comment] 2021-03-16 11:40
Do you know when this will be released?

**Comment by takb** [comment] 2021-03-17 06:15
This was released with version 6.2.0 in July 2020. Does your inquiry imply you are having issues with this parameter again?

**Comment by PeterDieter** [comment] 2021-03-17 06:28
I am getting the same error message when I am putting `continue_straight=True` in my query.

**Comment by takb** [comment] 2021-03-17 09:53
Okay, will re-investigate...

**Comment by takb** [comment] 2021-03-18 08:35
I did some investigation but could not reproduce. Could you please provide the exact query and the app.config file you used?

**Comment by PeterDieter** [comment] 2021-03-18 08:49
I did not deploy the server myself but use the free API. 
This is the python code that I use:
 ```
body = {'coordinates': [[-88.053228, 41.96406], [-88.063436, 41.984543], [-88.065683, 41.984596], [-88.064097, 41.985444]],
             'continue_straight': True}
headers = {
                'Accept': 'application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8',
                'Authorization': constants.ORS_KEY,
                'Content-Type': 'application/json; charset=utf-8'
            }
 r = requests.post('https://api.openrouteservice.org/v2/directions/driving-car', json=body, headers=headers).json()

```
`{'error': {'code': 2099, 'message': 'Heading is not (fully) supported for CHGraph. See issue #483'}, 'info': {'engine': {'version': '6.3.6', 'build_date': '2021-03-02T18:34:49Z'}, 'timestamp': 1616058327609}}`

**Closed as completed** 2021-03-24 10:56 UTC
