### ISSUE TITLE
docker-compose up-d stalling on Step 8

### ISSUE THREAD

**Issue by civil142** [GIScience/openrouteservice#604] opened 2019-10-16 07:20 UTC
I tried building the ORS using the instructions - it started well then this happened.

Step 8/29 : RUN apt-get update -qq
---> Running in d6d9889c2b1d
apt-get : The term 'apt-get' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:76
+ ... e = 'Stop'; $ProgressPreference = 'SilentlyContinue'; apt-get update  ...
+                                                           ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (apt-get:String) [], ParentConta
   insErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

ERROR: Service 'ors-app' failed to build: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; apt-get update -qq' returned a non-zero code: 1
PS

**Comment by nilsnolde** [comment] 2019-11-08 11:36
Sorry for the super late answer @civil142 ..

I'm not sure what the problem is, but I suspect some Windows Docker stuff here. The error very much sounds like a Powershell error, which suggests that Docker pulled a Windows image. I have no idea how to tell it to build Linux containers instead, but I'm sure with this clue you'll find that out yourself. Good luck with that!

Closing since no issue with our repo.

**Closed as completed by nilsnolde** 2019-11-08 11:36 UTC
Labels: wontfix | invalid
