### ISSUE TITLE
Getting a lot of HTTP 400 responses

### ISSUE THREAD

**Issue by CramericaIndustries** [GIScience/openrouteservice#594] opened 2019-09-30 10:39 UTC
Since about 2 weeks I'm getting a lot of HTTP 400 responses from the API. If I test one of the urls in my browser I get the HTTP 400 too, however if I hit the refresh button 2-3 times it suddenly works.

Example URL (**you need to add an API key**):
[https://api.openrouteservice.org/directions?coordinates=23.97466899999995,54.100236|23.982504000000063,54.099363|23.98706196672731,54.09833120710157&profile=foot-hiking&preference=shortest&format=geojson&units=m&geometry_format=geojson&instructions=false&elevation=true&extra_info=surface|waytype|steepness&**api_key=super-secret-API-key**](https://api.openrouteservice.org/directions?coordinates=23.97466899999995,54.100236|23.982504000000063,54.099363|23.98706196672731,54.09833120710157&profile=foot-hiking&preference=shortest&format=geojson&units=m&geometry_format=geojson&instructions=false&elevation=true&extra_info=surface|waytype|steepness&api_key=super-secret-API-key)

**Comment by rabidllama** [comment] 2019-10-02 07:28
Hi,

the reason for this is because we recently extended our server infrastructure so that now we have load balancing. This means that for each profile there are two servers, and the newer ones have extra security checks on them imposed by Tomcat. Because of that, all special characters (pipes, braces etc.) need to be encoded, which is best practice anyway as a number of services do not allow special characters in the URL request. So the reason you would get some that work and some that don't is that some requests would go to the old server which has not yet been updated to reject special characters, and some would go to the new ones that are. 

As a similar update to the other servers will likely happen soon, it is advisable to either fully encode such special characters (for example, a | should be encoded as %7C) or event better, use the v2 APII which uses POST body as that is much easier to read and generate (no more pipes or complex JSON structures in a URL).

**Comment by nilsnolde** [comment] 2019-10-09 09:50
Closing this as it's not a bug and no action will be taken from our side.

**Closed as completed by nilsnolde** 2019-10-09 09:50 UTC
