### ISSUE TITLE
Re-Integrate the traffic matching

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1621] opened 2023-12-05 09:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

We removed the matching percentage earlier because it was broken. We should repair and integrate it.

### Proposed solution

Integrate it.

**Comment by aoles** [comment] 2023-12-18 11:38
Duplicate of https://github.com/GIScience/openrouteservice/issues/1625

**Closed as completed by aoles** 2023-12-18 11:38 UTC
