### ISSUE TITLE
No extras in API response when requesting a round trip

### ISSUE THREAD

**Issue by olemeif** [GIScience/openrouteservice#1529] opened 2023-08-23 07:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

https://api.openrouteservice.org/v2/directions/driving-car

### POST Request Body

```JSON
{"coordinates":[[8.681495,49.41461]],
"extra_info":["waycategory","waytype"],
"instructions":"false",
"options":{"round_trip":{"length":10000,"points":5,"seed":1}}}
```

### Response

<details><summary>Response</summary>

```JSON

{
  "bbox":[8.668671,49.389508,8.710186,49.417392],
  "metadata":
  {
    "attribution":"openrouteservice.org | OpenStreetMap contributors",
    "service":"routing",
    "timestamp":1692774070350,
    "query":
    {
      "coordinates":[[8.681495,49.41461]],
      "profile":"driving-car",
      "format":"json",
      "extra_info":["waycategory","waytype"],
      "options":{"round_trip":{"length":10000,"points":5,"seed":1}}
    },
    "engine":{"version":"7.1.0","build_date":"2023-07-09T01:31:50Z","graph_date":"2023-08-20T10:24:28Z"}},
    "routes":
    [
      {
        "summary":{"distance":18234.3,"duration":3149.9},
        "bbox":[8.668671,49.389508,8.710186,49.417392],
        "geometry":"ghrlHir~s@?BjBl@`A\\p@i@wAkIOg@p@R|@LlAHL@~AUScG[_IEmAIuAcAyGSkCCkBG}CCiBAeCODoAVAq@AoCN?b@DR?\\CdDk@jDo@V?PHRVDPTv@LN^@f@UfB{@`Bw@PEVC^Jb@`@PLd@NlAGRAd@CFAj@CzAK`@I`@MZIHcAFe@HmB?MBsA?iE?SGgAkEwUu@cDQeAOgAScCWmDAIUUQAE@IL@hC?HiBHCkBA{AAoACgACeCe@HcDh@bDi@d@IK{FA[?_DBSDUTa@ZMX@@TPxDNdFDAJALCFuB^kEH[Tm@N[RUr@q@BEfAcAh@Yb@Sr@Wh@[X_@DK?OCKECuBTI?GG@GBInCsBb@k@~@sBJUZo@FED?DR@`ABtAP|A?RA\\g@~A?HBJJBJOPc@Zy@J]n@aDDH@LWdEG^u@dCGl@It@U`Aq@zAyAvBeAnBYj@[fAGr@Bx@Jv@V~@J\\v@jCVl@Z|@Ld@dA~HPj@RZRFlA?j@JfA^XZbCtDn@n@fAt@x@b@x@Xh@F`AAfAQ\\M~BqApByAVu@j@wDb@cC`@eB\\mANa@NSPSPIRE`G_@vBc@XOFIRg@Lg@LyA@sCG{AQmAMk@Qe@MUaAmAQa@{B_GKg@I{@?i@BWFSPSPEnAJ`A?d@Mf@]v@a@pCeANK`@c@DERQh@YNCN?t@R~Bv@NLTb@LP@ZDTpCbKHt@H|ACTMRMBMA{@_@u@Q]Mc@_@w@qAUSYK]@c@N_@FuASg@AWHa@PQRGR?RDRvAxBXj@Vr@DJNf@vA~FXjC?h@ErA?\\Bn@?lAGp@Q`AmBpHy@|DIh@K~@ElA@j@HtACJIHMIESIsCAqCJsBAKEKQCYTUZOb@Gd@CrACnEGpAAbA@jCCn@I`@St@[r@q@j@SRIJKZIZId@Mb@Q\\MTcB~@aAdAGDIHaA`@_@XIFi@j@GD_@B[CMCOAIJEP_@dEPDz@XFBt@V`@RJJHJPd@EHARBNFDH@HGNHT^TPXB~@GZAp@Hh@A|@Gx@OZI?A|AQxBS`AGhG_@rBKx@E`AExDOXAB?n@CfBChEIrAEDnC@fABnA@pAHhEHdGBrAHtEaAFuBJJhGtDQI_F?k@IuECsAiCNI@cCLeADk@B_CLe@BiAFk@@cBFUGO?}Pj@a@?}@?a@@g@@O?qBP]FWFE@SFa@LQLCb@SrAOn@c@xAk@xA_AbBiA~AQVa@Zc@`@iD~DQRo@x@g@r@Q\\GNMTLPvAbBz@hAdAvAvA~BJPDHcArE_AhDi@rA{AdD}@zBy@rBWn@^^`Al@LHgBdNHBICaAtHIj@{Ak@n@_Ft@cG?YEIOMeAgAiAdBwBnC}@hA}@hAm@v@YHYC}CeDQSWUk@u@}AqBaAmAoA_Bc@g@a@AeD@@sE?UG}AM}@Ma@a@eAk@u@c@y@Mi@Gc@Co@CiAA}FP_AFMNQl@QVBRHLLHRFXB`@?|BCVS`@MPa@JqA?oKN{@A[Aq@Bm@@O@iBB}EJ}@DwBHmCNcEJ?m@CeBCyBCe@O}E]qEa@qGCgA?sB?k@pD@vCRlFl@InB?x@",
        "way_points":[0,534],
        "legs":[]
      }
    ]
  }

```
</details>

### Current behavior

I am requesting a **round trip** with a length of 10000 meters from [8.681495,49.41461]. I am also requesting some extra_info. The latter does not show up in the response.

### Expected behavior

When requesting a normal direction with those extra_info, the response looks like this:
```JSON
{
"bbox": [ /* 4 items */ ], 
"metadata": { /* 5 items */ },
"routes":
[
  {
    "summary": { /* 2 items */ },
    "bbox": [ /* 4 items */ ],
    "geometry": "...", 
    "way_points": [ /* 2 items */ ],
    "legs": [ /* no items */ ],
    "extras": { /* 2 items */ }
  }
]
}
```
Note the extras under "legs", that are missing, when requesting a round-trip

### Openrouteservice Version

7.1.0

### Build date

2023-07-09T01:31:50Z

### Graph date

2023-08-20T10:24:28Z

### Forum Topic Link

https://ask.openrouteservice.org/t/no-extras-in-api-response-when-requesting-a-round-trip/5156

**Comment by moninm** [comment] 2023-12-05 23:22
Do you have correctly configured the config file ? I did the same thing and I have the extra infos.

**Comment by MichaelsJP** [comment] 2023-12-13 17:05
@muederotter Thanks for your feedback. I could just reproduce this. We'll look at this in time. If you have some spare hours, you're more than welcome to look into it and contribute to ors.

**Comment by MichaelsJP** [comment] 2023-12-13 17:15
@muederotter Thanks for your feedback. As far as I know, the extra_information should be under "extras".  I see that one in your response with 2 items. What's the content of that?

The legs part is indeed empty.

**Comment by MichaelsJP** [comment] 2024-01-09 15:00
Closing this due since we cannot to reproduce this error.

**Closed as completed by MichaelsJP** 2024-01-09 15:00 UTC
Labels: api
