### ISSUE TITLE
incorrect elevation in a route at routeservice

### ISSUE THREAD

**Issue by naalang** [GIScience/openrouteservice#553] opened 2019-06-16 09:40 UTC
When i ask the elevation at a route, the routeservice gives me the elevation of the map and not the elevation of the road him self.
But if you have a tunnel or a bridge the elevation isn't correct.
A tunnel in a mountain the elevation gives maybe the top of the mountain in stead of the elevation of the road surface.
So it isn't possible to calculate the correct descent or ascent of the road.

Is it possible to correct the elevation to the elevation of the road in stead of the elevation of the surface of the map?

**Comment by TimMcCauley** [comment] 2019-06-17 06:45
Hi @naalang - yes, this will be fixed in our next update. I will keep this open until then. Thanks and cheers, Tim

**Comment by rabidllama** [comment] 2020-04-30 06:42
Is this still a problem?

**Comment by aoles** [comment] 2020-04-30 11:26
Duplicate of #685.

**Closed as completed by aoles** 2020-04-30 11:26 UTC
