### ISSUE TITLE
extras field sometimes without value

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#411] opened 2019-02-13 15:49 UTC
Reported by a user. E.g. following query sometimes has an **empty** `extras` field:
https://api.openrouteservice.org/directions?api_key=key&coordinates=11.976793,51.488623%7C13.40732,52.52045&profile=foot-walking&preference=shortest&language=de&format=json&geometry_format=geojson&elevation=true&maneuvers=true&extra_info=steepness%7Csuitability%7Csurface%7Cwaycategory%7Cwaytype%7Ctraildifficulty&instructions=true

Try 10-20 times, it will show up. The key exists, but no value, i.e. `extras: {}` in the response.

It's a rather long route from Halle to Berlin. Sounds like a nasty thing to debug..

**Comment by takb** [comment] 2019-02-20 09:11
I've started looking into it, and I could reproduce the error on different profiles as well. With `profile=foot-walking` the error occurs 10-15% of the time, with `driving-car`, `driving-hgv` and `cycling-regular` with about 0.5-1% of calls. However, I could not reproduce the error locally, neither with development nor with master branch code. I'm suspecting the issue might be related to server configuration or load situation or something. How do I find out if there are errors logged on the servers corresponding to the failing calls?

**Comment by aoles** [comment] 2019-11-27 16:17
Same as #571 ?

**Comment by takb** [comment] 2019-11-27 16:23
Possible, now you mention it... As soon as the v6 code is deployed I'll run my repro code again to check, since #571 should be fixed now.

**Comment by rabidllama** [comment] 2020-04-30 06:49
Did this get fixed?

**Comment by takb** [comment] 2020-04-30 14:57
I've run my repro code several times just to make sure, this got fixed when #571 got fixed.

**Closed as completed by takb** 2020-04-30 14:57 UTC
