### ISSUE TITLE
[6099] Small matrix computation fails (5x5) over small region (cycling-regular profile)

### ISSUE THREAD

**Issue by loic-faure** [GIScience/openrouteservice#1039] opened 2021-08-17 12:28 UTC
I use the matrix API through python sdk which works well with cycling-regular profile.

But I found a strange case this morning when I tried to compute a 5 by 5 matrix in a small area of Paris but received a 500 response with error code 6099.
After some research on the error code, I found that can be caused by distances restrictions but the locations are very close in that case, as you can see on the map of Paris:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/53184130/129725387-162e8724-ed24-40b4-a7c3-07e6e6a364cf.png">

I manage to reproduce the issue with the API playground. Only 2 profiles are not working: cycling-regular and wheelchair.
`{"locations":[[2.3423911,48.8562003],[2.3622833,48.8658769],[2.3452095,48.8405038],[2.3421852,48.8534205],[2.3268684,48.8588037],[2.3423911,48.8562003],[2.3622833,48.8658769],[2.3452095,48.8405038],[2.3421852,48.8534205],[2.3268684,48.8588037]],"destinations":[5,6,7,8,9],"sources":[0,1,2,3,4]}`

I'm not sure this is a bug, but I would like to understand why that specific profile doesn't work in that case.

Thanks in advance for your time,
Loïc

**Comment by loic-faure** [comment] 2021-08-19 08:19
Hmm, seems like a bigger problem since I have the same result (Error 6099) for several other exemples.
It's working with cycling-mountain, strange behaviour for inner Paris.

**Comment by koebi** [comment] 2021-08-24 12:45
Hey,

I can only partially reproduce this. I tried your request with cycling-regular, and it seems to work just fine.

It does indeed not work with wheelchair, but this seems to be an issue with the routes themselves, as the regular directions endpoint doesn't reply with a valid route for some combination of waypoints.

In fact, this led me to play around with wheelchair a bit, and I cannot explain the following:

![Screenshot_2021-08-24 Openrouteservice Maps(1)](https://user-images.githubusercontent.com/4692974/130618527-79c190fc-d91f-448d-9cf2-31f30874cd97.png)

This is a regular residential road, and the wheelchair profile should easily allow routing there…

**Comment by koebi** [comment] 2021-08-25 11:06
Currently, the wheelchair profile doesn't allow routing here, since there is no sidewalk available.

This might be a tagging error. In this case, there's nothing the ors can dow.

However, in release 6.6.2, the `allow_unsuitable`-parameter will be introduced to allow wheelchair routing over unsuitable ways, like ones without sidewalks.

Note, that this won't apply to matrix requests, since they currently do not support all routing options available for the `directions`-endpoint.

**Closed as completed by koebi** 2021-08-25 11:06 UTC
