### ISSUE TITLE
Routing leaves highway unnecessarily

### ISSUE THREAD

**Issue by avanc** [GIScience/openrouteservice#506] opened 2019-04-25 18:49 UTC
#### Here's what I did
Create a route on a highway:
https://maps.openrouteservice.org/directions?n1=52.452583&n2=10.777234&n3=16&a=52.449975,10.781826,52.454028,10.773404&b=0&c=0&k1=en-US&k2=km

---
#### Here's what I got
![screenshot](https://user-images.githubusercontent.com/2905029/56686048-8e1e6500-66d3-11e9-8f69-135eb21dfc9a.png)

---
#### Here's what I was expecting
I would expect that the highway is not left.

---
#### Here's what I think could be improved
I had a look at the OSM data but couldn't find anything wrong. Let me know, if it isn't an OpenRouteService problem but an OSM data problem so I can fix it.

**Comment by jarek** [comment] 2019-05-08 15:23
This might be related/same underlying issue as #339

**Comment by HendrikLeuschner** [comment] 2019-06-17 10:57
Hi avanc,
thanks for the well written issue. This is indeed an ORS bug. We are investigating this issue. It is most likely caused by how we calculate the time it takes to traverse certain edges.

**Comment by takb** [comment] 2019-11-28 14:24
Will close this now since #622 will fix.

**Closed as completed** 2019-11-28 14:25 UTC
